HTML and Inspecting a Web page

Scraping Data from a Website + Pandas

In [1]:
from bs4 import BeautifulSoup
import requests

In [2]:
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Safari/605.1.15"

'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Safari/605.1.15'

In [3]:
headers = {'User-Agent' : 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Safari/605.1.15'}

url = 'https://en.wikipedia.org/wiki/List_of_largest_companies_in_Indonesia'

page = requests.get(url, headers=headers)

soup = BeautifulSoup(page.text, 'html')

In [4]:
print(soup)

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard" dir="ltr" lang="en">
<head>
<meta charset="utf-8"/>
<title>List of largest companies in Indonesia - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"07da0ea8-e661-42a8-b752-b3b60a692a78","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_largest_companies_in_Indonesia","wgTitle":"List of largest companies in Indonesia","wgCurRevisionId":1289436114,"wgRevisionId":1289436114,"wgArticleId":61423364,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description is different from Wikidata","Lists of largest private companies by country","Lists of companies of Indonesia","Holding companies by country"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"List_of_largest_companies_in_Indonesia","wgRelevantArticleId":61423364,"wgTempUserName":null,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}},"namespaces":[0,4]},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditForceShowCaptcha":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgMediaViewerMobileBeta":false,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":7000,"wgParsoidHtmlVersion":"2.8.0","parsermigration-parsoid":true,"wgPageAssessments":{"Indonesia":{"class":"List","importance":"Low"},"Lists":{"class":"List","importance":"Unknown"},"Project-independent assessment":{"class":"List","importance":""}},"wgTestKitchenUserExperiments":{"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[]},"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgULSLanguageSelectorV2Enabled":true,"wgWikibaseItemId":"Q66789388","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"wgPersonalDashboardMenuVisible":false};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.cite.parsoid.styles":"ready","ext.cite.styles":"ready","mediawiki.skinning.content.parsoid":"ready","ext.wikimediamessages.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","site","mediawiki.page.ready","jquery.tablesorter","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","ext.testKitchen","ext.wikimediaCustomizations.donorAccountCreation","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.quicksurveys.init"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});mw.user.options.set({"usecodemirror":1});
}];});});</script>
<link href="/w/load.php?lang=en&amp;modules=ext.cite.parsoid.styles%7Cext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediamessages.styles%7Cjquery.tablesorter.styles%7Cmediawiki.skinning.content.parsoid%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>
<meta content="" name="ResourceLoaderDynamicStyles"/>
<link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<meta content="MediaWiki 1.47.0-wmf.21" name="generator"/>
<meta content="origin" name="referrer"/>
<meta content="origin-when-cross-origin" name="referrer"/>
<meta content="max-image-preview:standard" name="robots"/>
<meta content="telephone=no" name="format-detection"/>
<meta content="width=1120" name="viewport"/>
<meta content="List of largest companies in Indonesia - Wikipedia" property="og:title"/>
<meta content="website" property="og:type"/>
<link href="/w/index.php?title=List_of_largest_companies_in_Indonesia&amp;action=edit" rel="alternate" title="Edit this page" type="application/x-wiki"/>
<link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
<link href="/static/favicon/wikipedia.ico" rel="icon"/>
<link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
<link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
<link href="https://en.wikipedia.org/wiki/List_of_largest_companies_in_Indonesia" rel="canonical"/>
<link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
<link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
<link href="//meta.wikimedia.org" rel="dns-prefetch"/>
<link href="auth.wikimedia.org" rel="dns-prefetch"/>
</head>
<body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-List_of_largest_companies_in_Indonesia rootpage-List_of_largest_companies_in_Indonesia skin-vector-2022 action-view">
<div aria-live="polite" class="mw-aria-live-region" id="mw-aria-live-region"></div><a class="mw-jump-link" href="#bodyContent">Jump to content</a>
<div class="vector-header-container">
<header class="vector-header mw-header no-font-mode-scale">
<div class="vector-header-start">
<nav aria-label="Site" class="vector-main-menu-landmark">
<div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">
<input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label"><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu cdx-button__icon"></span>
<span class="vector-dropdown-label-text">Main menu</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
<div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
<div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
<div class="vector-pinnable-header-label">Main menu</div>
<button aria-label="Move Main menu to sidebar" class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">move to sidebar</button>
<button aria-label="Hide Main menu" class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">hide</button>
</div>
<div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
<div class="vector-menu-heading">
		Navigation
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-mainpage-description"><a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]"><span>Main page</span></a></li><li class="mw-list-item" id="n-contents"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li class="mw-list-item" id="n-currentevents"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li class="mw-list-item" id="n-randompage"><a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]"><span>Random article</span></a></li><li class="mw-list-item" id="n-aboutsite"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li class="mw-list-item" id="n-contactpage"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
<div class="vector-menu-heading">
		Contribute
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-help"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li class="mw-list-item" id="n-introduction"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li class="mw-list-item" id="n-portal"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li class="mw-list-item" id="n-recentchanges"><a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]"><span>Recent changes</span></a></li><li class="mw-list-item" id="n-upload"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li><li class="mw-list-item" id="n-specialpages"><a accesskey="q" href="/wiki/Special:SpecialPages" title="A list of all special pages [q]"><span>Special pages</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</nav>
<a class="mw-logo" href="/wiki/Main_Page">
<img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/enwiki-25.svg" width="50"/>
<span class="mw-logo-container skin-invert">
<img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;"/>
<img alt="The Free Encyclopedia" class="mw-logo-tagline" height="11" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" style="width: 8.75em; height: 0.6875em;" width="140"/>
</span>
</a>
</div>
<div class="vector-header-end">
<div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
<a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search cdx-button__icon"></span>
<span>Search</span>
</a>
<div class="vector-typeahead-search-container">
<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
<form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
<div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
<div class="cdx-text-input cdx-text-input--has-start-icon">
<input accesskey="f" aria-label="Search Wikipedia" autocapitalize="none" autocomplete="off" class="cdx-text-input__input mw-searchInput" id="searchInput" name="search" placeholder="Search Wikipedia" spellcheck="false" title="Search Wikipedia [f]" type="search"/>
<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>
</div>
<input name="title" type="hidden" value="Special:Search"/>
</div>
<button class="cdx-button cdx-search-input__end-button">Search</button>
</form>
</div>
</div>
</div>
<nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
<div class="vector-user-links-main">
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<nav aria-label="Appearance" class="vector-appearance-landmark">
<div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
<input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label"><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance cdx-button__icon"></span>
<span class="vector-dropdown-label-text">Appearance</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
</div>
</div>
</div>
</nav>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item vector-menu-item--collapsible" id="pt-sitesupport-2"><a class="" data-mw-donate-attempt="top_link" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a>
</li>
<li class="mw-list-item vector-menu-item--collapsible" id="pt-createaccount-2"><a class="" data-mw-interface="" href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+largest+companies+in+Indonesia" title="You are encouraged to create an account and log in; however, it is not mandatory"><span>Create account</span></a>
</li>
<li class="mw-list-item vector-menu-item--collapsible" id="pt-login-2"><a accesskey="o" class="" data-mw-interface="" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+largest+companies+in+Indonesia" title="You're encouraged to log in; however, it's not mandatory. [o]"><span>Log in</span></a>
</li>
</ul>
</div>
</div>
</div>
<div class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out vector-user-links-dropdown--collapsible" id="vector-user-links-dropdown" title="Log in and more options">
<input aria-haspopup="true" aria-label="Personal tools" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-user-links-dropdown" id="vector-user-links-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-user-links-dropdown-checkbox" id="vector-user-links-dropdown-label"><span class="vector-icon mw-ui-icon-userAvatar mw-ui-icon-wikimedia-userAvatar cdx-button__icon"></span>
<span class="vector-dropdown-label-text">Personal tools</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-menu mw-portlet mw-portlet-personal" id="p-personal" title="User menu">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item vector-menu-item--collapsible" id="pt-sitesupport"><a class="" data-mw-donate-attempt="top_link" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span class="vector-icon mw-ui-icon-heart mw-ui-icon-wikimedia-heart cdx-button__icon"></span>
<span>Donate</span></a>
</li>
<li class="mw-list-item vector-menu-item--collapsible" id="pt-createaccount"><a class="" data-mw-interface="" href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+largest+companies+in+Indonesia" title="You are encouraged to create an account and log in; however, it is not mandatory"><span class="vector-icon mw-ui-icon-userAvatar mw-ui-icon-wikimedia-userAvatar cdx-button__icon"></span>
<span>Create account</span></a>
</li>
<li class="mw-list-item vector-menu-item--collapsible" id="pt-login"><a accesskey="o" class="" data-mw-interface="" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+largest+companies+in+Indonesia" title="You're encouraged to log in; however, it's not mandatory. [o]"><span class="vector-icon mw-ui-icon-logIn mw-ui-icon-wikimedia-logIn cdx-button__icon"></span>
<span>Log in</span></a>
</li>
</ul>
</div>
</div>
</div>
</div>
</nav>
</div>
</header>
</div>
<div class="mw-page-container">
<div class="mw-page-container-inner">
<div class="vector-sitenotice-container">
<div id="siteNotice"><!-- CentralNotice --></div>

In [30]:
# Select the table
soup.find_all('table')[0]

<table class="wikitable sortable" id="mwGg">
<tbody id="mwGw"><tr id="mwHA"><th id="mwHQ">Rank</th>
<th id="mwHg">Name</th>
<th id="mwHw">Industry</th>
<th id="mwIA">Revenue<br id="mwIQ"/><small id="mwIg">(USD millions)</small></th>
<th id="mwIw">Profits<br id="mwJA"/><small id="mwJQ">(USD millions)</small></th>
<th id="mwJg">Employees</th>
<th id="mwJw">Headquarters</th>
<th id="mwKA">Type</th></tr>
<tr id="mwKQ">
<td id="mwKg">1</td>
<td id="mwKw"><a href="https://en.wikipedia.org/wiki/Pertamina" id="mwLA" rel="mw:WikiLink" title="Pertamina">Pertamina</a></td>
<td id="mwLQ"><a href="https://en.wikipedia.org/wiki/Fossil_fuel" id="mwLg" rel="mw:WikiLink" title="Fossil fuel">Oil and Gas</a></td>
<td id="mwLw" style="text-align:center;">75,788</td>
<td id="mwMA" style="text-align:center;">4,441</td>
<td id="mwMQ" style="text-align:center;">40,415</td>
<td id="mwMg"><a href="https://en.wikipedia.org/wiki/Jakarta" id="mwMw" rel="mw:WikiLink" title="Jakarta">Jakarta</a></td>
<td id="mwNA">SOE</td></tr>
<tr id="mwNQ">
<td id="mwNg">2</td>
<td id="mwNw"><a href="https://en.wikipedia.org/wiki/Perusahaan_Listrik_Negara" id="mwOA" rel="mw:WikiLink" title="Perusahaan Listrik Negara">Perusahaan Listrik Negara</a></td>
<td id="mwOQ"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Utilities" id="mwOg" rel="mw:WikiLink" title="Utilities">Utilities</a></td>
<td id="mwOw" style="text-align:center;">32,013</td>
<td id="mwPA" style="text-align:center;">1,446</td>
<td id="mwPQ" style="text-align:center;">51,245</td>
<td id="mwPg">Jakarta</td>
<td id="mwPw">SOE</td></tr>
<tr id="mwQA">
<td id="mwQQ">3</td>
<td id="mwQg"><a href="https://en.wikipedia.org/wiki/Bank_Rakyat_Indonesia" id="mwQw" rel="mw:WikiLink" title="Bank Rakyat Indonesia">Bank Rakyat Indonesia</a></td>
<td id="mwRA"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Banking" id="mwRQ" rel="mw:WikiLink" title="Banking">Banking</a></td>
<td id="mwRg" style="text-align:center;">14,917</td>
<td id="mwRw" style="text-align:center;">3,948</td>
<td id="mwSA" style="text-align:center;">77,739</td>
<td id="mwSQ">Jakarta</td>
<td id="mwSg">SOE</td></tr>
<tr id="mwSw">
<td id="mwTA">4</td>
<td id="mwTQ"><a href="https://en.wikipedia.org/wiki/Bank_Mandiri" id="mwTg" rel="mw:WikiLink" title="Bank Mandiri">Bank Mandiri</a></td>
<td id="mwTw">Banking</td>
<td id="mwUA" style="text-align:center;">11,515</td>
<td id="mwUQ" style="text-align:center;">3,616</td>
<td id="mwUg" style="text-align:center;">36,872</td>
<td id="mwUw">Jakarta</td>
<td id="mwVA">SOE</td></tr>
<tr id="mwVQ">
<td id="mwVg">5</td>
<td id="mwVw"><a href="https://en.wikipedia.org/wiki/Telkom_Indonesia" id="mwWA" rel="mw:WikiLink" title="Telkom Indonesia">Telkom Indonesia</a></td>
<td id="mwWQ"><a href="https://en.wikipedia.org/wiki/Telecommunications" id="mwWg" rel="mw:WikiLink" title="Telecommunications">Telecommunications</a></td>
<td id="mwWw" style="text-align:center;">9,801</td>
<td id="mwXA" style="text-align:center;">1,613</td>
<td id="mwXQ" style="text-align:center;">23,064</td>
<td id="mwXg">Jakarta</td>
<td id="mwXw">SOE</td></tr>
<tr id="mwYA">
<td id="mwYQ">6</td>
<td id="mwYg"><a href="https://en.wikipedia.org/wiki/Gudang_Garam" id="mwYw" rel="mw:WikiLink" title="Gudang Garam">Gudang Garam</a></td>
<td id="mwZA">Tobacco</td>
<td id="mwZQ" style="text-align:center;">7,813</td>
<td id="mwZg" style="text-align:center;">350</td>
<td id="mwZw" style="text-align:center;">25,961</td>
<td id="mwaA"><a href="https://en.wikipedia.org/wiki/Kediri_(city)" id="mwaQ" rel="mw:WikiLink" title="Kediri (city)">Kediri</a></td>
<td id="mwag">Private</td></tr>
<tr id="mwaw">
<td id="mwbA">7</td>
<td id="mwbQ"><a href="https://en.wikipedia.org/wiki/Bank_Central_Asia" id="mwbg" rel="mw:WikiLink" title="Bank Central Asia">Bank Central Asia</a></td>
<td id="mwbw">Banking</td>
<td id="mwcA" style="text-align:center;">7,371</td>
<td id="mwcQ" style="text-align:center;">3,195</td>
<td id="mwcg" style="text-align:center;">25,486</td>
<td id="mwcw">Jakarta</td>
<td id="mwdA">Private</td></tr>
<tr id="mwdQ">
<td id="mwdg">8</td>
<td id="mwdw"><a href="https://en.wikipedia.org/wiki/Indofood" id="mweA" rel="mw:WikiLink" title="Indofood">Indofood</a></td>
<td id="mweQ"><a href="https://en.wikipedia.org/wiki/Food" id="mweg" rel="mw:WikiLink" title="Food">Food</a></td>
<td id="mwew" style="text-align:center;">7,337</td>
<td id="mwfA" style="text-align:center;">535</td>
<td id="mwfQ" style="text-align:center;">81,367</td>
<td id="mwfg">Jakarta</td>
<td id="mwfw">Private</td></tr>
<tr id="mwgA">
<td id="mwgQ">9</td>
<td id="mwgg"><a href="https://en.wikipedia.org/wiki/Inalum" id="mwgw" rel="mw:WikiLink" title="Inalum">Inalum</a></td>
<td id="mwhA"><a href="https://en.wikipedia.org/wiki/Aluminium" id="mwhQ" rel="mw:WikiLink" title="Aluminium">Aluminium</a></td>
<td id="mwhg" style="text-align:center;">7,088</td>
<td id="mwhw" style="text-align:center;">1,599</td>
<td id="mwiA" style="text-align:center;">10,422</td>
<td id="mwiQ"><a href="https://en.wikipedia.org/wiki/Batubara_Regency" id="mwig" rel="mw:WikiLink" title="Batubara Regency">Batubara</a></td>
<td id="mwiw">SOE</td></tr>
<tr id="mwjA">
<td id="mwjQ">10</td>
<td id="mwjg"><a href="https://en.wikipedia.org/wiki/Alfamart" id="mwjw" rel="mw:WikiLink" title="Alfamart">Alfamart</a></td>
<td id="mwkA"><a href="https://en.wikipedia.org/wiki/Retail" id="mwkQ" rel="mw:WikiLink" title="Retail">Retail</a></td>
<td id="mwkg" style="text-align:center;">7,025</td>
<td id="mwkw" style="text-align:center;">224</td>
<td id="mwlA" style="text-align:center;">195,757</td>
<td id="mwlQ"><a href="https://en.wikipedia.org/wiki/Tangerang" id="mwlg" rel="mw:WikiLink" title="Tangerang">Tangerang</a></td>
<td id="mwlw">Private</td></tr>
<tr id="mwmA">
<td id="mwmQ">11</td>
<td id="mwmg"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Adaro_Energy" id="mwmw" rel="mw:WikiLink" title="Adaro Energy">Adaro Energy</a></td>
<td id="mwnA"><a href="https://en.wikipedia.org/wiki/Coal_mining" id="mwnQ" rel="mw:WikiLink" title="Coal mining">Coal mining</a></td>
<td id="mwng" style="text-align:center;">6,518</td>
<td id="mwnw" style="text-align:center;">1,641</td>
<td id="mwoA" style="text-align:center;">14,697</td>
<td id="mwoQ"><a href="https://en.wikipedia.org/wiki/Tabalong_Regency" id="mwog" rel="mw:WikiLink" title="Tabalong Regency">Tabalong</a></td>
<td id="mwow">Private</td></tr>
<tr id="mwpA">
<td id="mwpQ">12</td>
<td id="mwpg"><a href="https://en.wikipedia.org/wiki/Bank_Negara_Indonesia" id="mwpw" rel="mw:WikiLink" title="Bank Negara Indonesia">Bank Negara Indonesia</a></td>
<td id="mwqA">Banking</td>
<td id="mwqQ" style="text-align:center;">5,448</td>
<td id="mwqg" style="text-align:center;">1,373</td>
<td id="mwqw" style="text-align:center;">27,570</td>
<td id="mwrA">Jakarta</td>
<td id="mwrQ">SOE</td></tr>
<tr id="mwrg">
<td id="mwrw">13</td>
<td id="mwsA"><a href="https://en.wikipedia.org/wiki/Pupuk_Kalimantan_Timur" id="mwsQ" rel="mw:WikiLink" title="Pupuk Kalimantan Timur">Pupuk Kalimantan Timur</a></td>
<td id="mwsg"><a href="https://en.wikipedia.org/wiki/Fertilizer" id="mwsw" rel="mw:WikiLink" title="Fertilizer">Fertilizer</a></td>
<td id="mwtA" style="text-align:center;">5,207</td>
<td id="mwtQ" style="text-align:center;">407</td>
<td id="mwtg" style="text-align:center;">7,441</td>
<td id="mwtw"><a href="https://en.wikipedia.org/wiki/Bontang" id="mwuA" rel="mw:WikiLink" title="Bontang">Bontang</a></td>
<td id="mwuQ">SOE</td></tr>
<tr id="mwug">
<td id="mwuw">14</td>
<td id="mwvA"><a class="new" data-mw-i18n='{"title":{"lang":"x-page","key":"red-link-title","params":["Dian Swastatika Sentosa"]}}' href="https://en.wikipedia.org/wiki/Dian_Swastatika_Sentosa?action=edit&amp;redlink=1" id="mwvQ" rel="mw:WikiLink" title="Dian Swastatika Sentosa (page does not exist)" typeof="mw:LocalizedAttrs">Dian Swastatika Sentosa</a></td>
<td id="mwvg">Mining</td>
<td id="mwvw" style="text-align:center;">5,015</td>
<td id="mwwA" style="text-align:center;">462</td>
<td id="mwwQ" style="text-align:center;">2,368</td>
<td id="mwwg">Jakarta</td>
<td id="mwww">Private</td></tr>
<tr id="mwxA">
<td id="mwxQ">15</td>
<td id="mwxg"><a class="new" data-mw-i18n='{"title":{"lang":"x-page","key":"red-link-title","params":["Erajaya"]}}' href="https://en.wikipedia.org/wiki/Erajaya?action=edit&amp;redlink=1" id="mwxw" rel="mw:WikiLink" title="Erajaya (page does not exist)" typeof="mw:LocalizedAttrs">Erajaya</a></td>
<td id="mwyA">Retail</td>
<td id="mwyQ" style="text-align:center;">3,950</td>
<td id="mwyg" style="text-align:center;">54</td>
<td id="mwyw" style="text-align:center;">5,675</td>
<td id="mwzA">Jakarta</td>
<td id="mwzQ">Private</td></tr>
<tr id="mwzg">
<td id="mwzw">16</td>
<td id="mw0A"><a class="new" data-mw-i18n='{"title":{"lang":"x-page","key":"red-link-title","params":["Bayan Resources"]}}' href="https://en.wikipedia.org/wiki/Bayan_Resources?action=edit&amp;redlink=1" id="mw0Q" rel="mw:WikiLink" title="Bayan Resources (page does not exist)" typeof="mw:LocalizedAttrs">Bayan Resources</a></td>
<td id="mw0g">Coal mining</td>
<td id="mw0w" style="text-align:center;">3,581</td>
<td id="mw1A" style="text-align:center;">1,239</td>
<td id="mw1Q" style="text-align:center;">3,819</td>
<td id="mw1g">Jakarta</td>
<td id="mw1w">Private</td></tr>
<tr id="mw2A">
<td id="mw2Q">17</td>
<td id="mw2g"><a class="new" data-mw-i18n='{"title":{"lang":"x-page","key":"red-link-title","params":["Indah Kiat Pulp &amp; Paper"]}}' href="https://en.wikipedia.org/wiki/Indah_Kiat_Pulp_&amp;_Paper?action=edit&amp;redlink=1" id="mw2w" rel="mw:WikiLink" title="Indah Kiat Pulp &amp; Paper (page does not exist)" typeof="mw:LocalizedAttrs">Indah Kiat Pulp &amp; Paper</a></td>
<td id="mw3A"><a href="https://en.wikipedia.org/wiki/Pulp_and_paper_industry" id="mw3Q" rel="mw:WikiLink" title="Pulp and paper industry">Pulp and paper</a></td>
<td id="mw3g" style="text-align:center;">3,479</td>
<td id="mw3w" style="text-align:center;">412</td>
<td id="mw4A" style="text-align:center;">11,000</td>
<td id="mw4Q">Jakarta</td>
<td id="mw4g">Private</td></tr>
<tr id="mw4w">
<td id="mw5A">18</td>
<td id="mw5Q"><a href="https://en.wikipedia.org/wiki/Indosat" id="mw5g" rel="mw:WikiLink" title="Indosat">Indosat</a></td>
<td id="mw5w"><a href="https://en.wikipedia.org/wiki/Telecommunications" id="mw6A" rel="mw:WikiLink" title="Telecommunications">Telecommunications</a></td>
<td id="mw6Q" style="text-align:center;">3,365</td>
<td id="mw6g" style="text-align:center;">296</td>
<td id="mw6w" style="text-align:center;">4,041</td>
<td id="mw7A">Jakarta</td>
<td id="mw7Q">Private</td></tr>
<tr id="mw7g">
<td id="mw7w">19</td>
<td id="mw8A"><a class="new" data-mw-i18n='{"title":{"lang":"x-page","key":"red-link-title","params":["Indika Energy"]}}' href="https://en.wikipedia.org/wiki/Indika_Energy?action=edit&amp;redlink=1" id="mw8Q" rel="mw:WikiLink" title="Indika Energy (page does not exist)" typeof="mw:LocalizedAttrs">Indika Energy</a></td>
<td id="mw8g"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Oil_and_Gas" id="mw8w" rel="mw:WikiLink" title="Oil and Gas">Oil and gas equipment</a></td>
<td id="mw9A" style="text-align:center;">3,027</td>
<td id="mw9Q" style="text-align:center;">120</td>
<td id="mw9g" style="text-align:center;">3,189</td>
<td id="mw9w">Jakarta</td>
<td id="mw-A">Private</td></tr>
<tr id="mw-Q">
<td id="mw-g">20</td>
<td id="mw-w"><a href="https://en.wikipedia.org/wiki/Garuda_Indonesia" id="mw_A" rel="mw:WikiLink" title="Garuda Indonesia">Garuda Indonesia</a></td>
<td id="mw_Q"><a href="https://en.wikipedia.org/wiki/Airline" id="mw_g" rel="mw:WikiLink" title="Airline">Airline</a></td>
<td id="mw_w" style="text-align:center;">2,937</td>
<td id="mwAQA" style="text-align:center;">250</td>
<td id="mwAQE" style="text-align:center;">4,401</td>
<td id="mwAQI">Jakarta</td>
<td id="mwAQM">SOE</td></tr>
</tbody></table>

In [31]:
table = soup.find_all('table')[0]

In [32]:
print(table)

<table class="wikitable sortable" id="mwGg">
<tbody id="mwGw"><tr id="mwHA"><th id="mwHQ">Rank</th>
<th id="mwHg">Name</th>
<th id="mwHw">Industry</th>
<th id="mwIA">Revenue<br id="mwIQ"/><small id="mwIg">(USD millions)</small></th>
<th id="mwIw">Profits<br id="mwJA"/><small id="mwJQ">(USD millions)</small></th>
<th id="mwJg">Employees</th>
<th id="mwJw">Headquarters</th>
<th id="mwKA">Type</th></tr>
<tr id="mwKQ">
<td id="mwKg">1</td>
<td id="mwKw"><a href="https://en.wikipedia.org/wiki/Pertamina" id="mwLA" rel="mw:WikiLink" title="Pertamina">Pertamina</a></td>
<td id="mwLQ"><a href="https://en.wikipedia.org/wiki/Fossil_fuel" id="mwLg" rel="mw:WikiLink" title="Fossil fuel">Oil and Gas</a></td>
<td id="mwLw" style="text-align:center;">75,788</td>
<td id="mwMA" style="text-align:center;">4,441</td>
<td id="mwMQ" style="text-align:center;">40,415</td>
<td id="mwMg"><a href="https://en.wikipedia.org/wiki/Jakarta" id="mwMw" rel="mw:WikiLink" title="Jakarta">Jakarta</a></td>
<td id="mwNA">SOE</td></tr>
<tr id="mwNQ">
<td id="mwNg">2</td>
<td id="mwNw"><a href="https://en.wikipedia.org/wiki/Perusahaan_Listrik_Negara" id="mwOA" rel="mw:WikiLink" title="Perusahaan Listrik Negara">Perusahaan Listrik Negara</a></td>
<td id="mwOQ"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Utilities" id="mwOg" rel="mw:WikiLink" title="Utilities">Utilities</a></td>
<td id="mwOw" style="text-align:center;">32,013</td>
<td id="mwPA" style="text-align:center;">1,446</td>
<td id="mwPQ" style="text-align:center;">51,245</td>
<td id="mwPg">Jakarta</td>
<td id="mwPw">SOE</td></tr>
<tr id="mwQA">
<td id="mwQQ">3</td>
<td id="mwQg"><a href="https://en.wikipedia.org/wiki/Bank_Rakyat_Indonesia" id="mwQw" rel="mw:WikiLink" title="Bank Rakyat Indonesia">Bank Rakyat Indonesia</a></td>
<td id="mwRA"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Banking" id="mwRQ" rel="mw:WikiLink" title="Banking">Banking</a></td>
<td id="mwRg" style="text-align:center;">14,917</td>
<td id="mwRw" style="text-align:center;">3,948</td>
<td id="mwSA" style="text-align:center;">77,739</td>
<td id="mwSQ">Jakarta</td>
<td id="mwSg">SOE</td></tr>
<tr id="mwSw">
<td id="mwTA">4</td>
<td id="mwTQ"><a href="https://en.wikipedia.org/wiki/Bank_Mandiri" id="mwTg" rel="mw:WikiLink" title="Bank Mandiri">Bank Mandiri</a></td>
<td id="mwTw">Banking</td>
<td id="mwUA" style="text-align:center;">11,515</td>
<td id="mwUQ" style="text-align:center;">3,616</td>
<td id="mwUg" style="text-align:center;">36,872</td>
<td id="mwUw">Jakarta</td>
<td id="mwVA">SOE</td></tr>
<tr id="mwVQ">
<td id="mwVg">5</td>
<td id="mwVw"><a href="https://en.wikipedia.org/wiki/Telkom_Indonesia" id="mwWA" rel="mw:WikiLink" title="Telkom Indonesia">Telkom Indonesia</a></td>
<td id="mwWQ"><a href="https://en.wikipedia.org/wiki/Telecommunications" id="mwWg" rel="mw:WikiLink" title="Telecommunications">Telecommunications</a></td>
<td id="mwWw" style="text-align:center;">9,801</td>
<td id="mwXA" style="text-align:center;">1,613</td>
<td id="mwXQ" style="text-align:center;">23,064</td>
<td id="mwXg">Jakarta</td>
<td id="mwXw">SOE</td></tr>
<tr id="mwYA">
<td id="mwYQ">6</td>
<td id="mwYg"><a href="https://en.wikipedia.org/wiki/Gudang_Garam" id="mwYw" rel="mw:WikiLink" title="Gudang Garam">Gudang Garam</a></td>
<td id="mwZA">Tobacco</td>
<td id="mwZQ" style="text-align:center;">7,813</td>
<td id="mwZg" style="text-align:center;">350</td>
<td id="mwZw" style="text-align:center;">25,961</td>
<td id="mwaA"><a href="https://en.wikipedia.org/wiki/Kediri_(city)" id="mwaQ" rel="mw:WikiLink" title="Kediri (city)">Kediri</a></td>
<td id="mwag">Private</td></tr>
<tr id="mwaw">
<td id="mwbA">7</td>
<td id="mwbQ"><a href="https://en.wikipedia.org/wiki/Bank_Central_Asia" id="mwbg" rel="mw:WikiLink" title="Bank Central Asia">Bank Central Asia</a></td>
<td id="mwbw">Banking</td>
<td id="mwcA" style="text-align:center;">7,371</td>
<td id="mwcQ" style="text-align:center;">3,195</td>
<td id="mwcg" style="text-align:center;">25,486</td>
<td id="mwcw">Jakarta</td>
<td id="mwdA">Private</td></tr>
<tr id="mwdQ">
<td id="mwdg">8</td>
<td id="mwdw"><a href="https://en.wikipedia.org/wiki/Indofood" id="mweA" rel="mw:WikiLink" title="Indofood">Indofood</a></td>
<td id="mweQ"><a href="https://en.wikipedia.org/wiki/Food" id="mweg" rel="mw:WikiLink" title="Food">Food</a></td>
<td id="mwew" style="text-align:center;">7,337</td>
<td id="mwfA" style="text-align:center;">535</td>
<td id="mwfQ" style="text-align:center;">81,367</td>
<td id="mwfg">Jakarta</td>
<td id="mwfw">Private</td></tr>
<tr id="mwgA">
<td id="mwgQ">9</td>
<td id="mwgg"><a href="https://en.wikipedia.org/wiki/Inalum" id="mwgw" rel="mw:WikiLink" title="Inalum">Inalum</a></td>
<td id="mwhA"><a href="https://en.wikipedia.org/wiki/Aluminium" id="mwhQ" rel="mw:WikiLink" title="Aluminium">Aluminium</a></td>
<td id="mwhg" style="text-align:center;">7,088</td>
<td id="mwhw" style="text-align:center;">1,599</td>
<td id="mwiA" style="text-align:center;">10,422</td>
<td id="mwiQ"><a href="https://en.wikipedia.org/wiki/Batubara_Regency" id="mwig" rel="mw:WikiLink" title="Batubara Regency">Batubara</a></td>
<td id="mwiw">SOE</td></tr>
<tr id="mwjA">
<td id="mwjQ">10</td>
<td id="mwjg"><a href="https://en.wikipedia.org/wiki/Alfamart" id="mwjw" rel="mw:WikiLink" title="Alfamart">Alfamart</a></td>
<td id="mwkA"><a href="https://en.wikipedia.org/wiki/Retail" id="mwkQ" rel="mw:WikiLink" title="Retail">Retail</a></td>
<td id="mwkg" style="text-align:center;">7,025</td>
<td id="mwkw" style="text-align:center;">224</td>
<td id="mwlA" style="text-align:center;">195,757</td>
<td id="mwlQ"><a href="https://en.wikipedia.org/wiki/Tangerang" id="mwlg" rel="mw:WikiLink" title="Tangerang">Tangerang</a></td>
<td id="mwlw">Private</td></tr>
<tr id="mwmA">
<td id="mwmQ">11</td>
<td id="mwmg"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Adaro_Energy" id="mwmw" rel="mw:WikiLink" title="Adaro Energy">Adaro Energy</a></td>
<td id="mwnA"><a href="https://en.wikipedia.org/wiki/Coal_mining" id="mwnQ" rel="mw:WikiLink" title="Coal mining">Coal mining</a></td>
<td id="mwng" style="text-align:center;">6,518</td>
<td id="mwnw" style="text-align:center;">1,641</td>
<td id="mwoA" style="text-align:center;">14,697</td>
<td id="mwoQ"><a href="https://en.wikipedia.org/wiki/Tabalong_Regency" id="mwog" rel="mw:WikiLink" title="Tabalong Regency">Tabalong</a></td>
<td id="mwow">Private</td></tr>
<tr id="mwpA">
<td id="mwpQ">12</td>
<td id="mwpg"><a href="https://en.wikipedia.org/wiki/Bank_Negara_Indonesia" id="mwpw" rel="mw:WikiLink" title="Bank Negara Indonesia">Bank Negara Indonesia</a></td>
<td id="mwqA">Banking</td>
<td id="mwqQ" style="text-align:center;">5,448</td>
<td id="mwqg" style="text-align:center;">1,373</td>
<td id="mwqw" style="text-align:center;">27,570</td>
<td id="mwrA">Jakarta</td>
<td id="mwrQ">SOE</td></tr>
<tr id="mwrg">
<td id="mwrw">13</td>
<td id="mwsA"><a href="https://en.wikipedia.org/wiki/Pupuk_Kalimantan_Timur" id="mwsQ" rel="mw:WikiLink" title="Pupuk Kalimantan Timur">Pupuk Kalimantan Timur</a></td>
<td id="mwsg"><a href="https://en.wikipedia.org/wiki/Fertilizer" id="mwsw" rel="mw:WikiLink" title="Fertilizer">Fertilizer</a></td>
<td id="mwtA" style="text-align:center;">5,207</td>
<td id="mwtQ" style="text-align:center;">407</td>
<td id="mwtg" style="text-align:center;">7,441</td>
<td id="mwtw"><a href="https://en.wikipedia.org/wiki/Bontang" id="mwuA" rel="mw:WikiLink" title="Bontang">Bontang</a></td>
<td id="mwuQ">SOE</td></tr>
<tr id="mwug">
<td id="mwuw">14</td>
<td id="mwvA"><a class="new" data-mw-i18n='{"title":{"lang":"x-page","key":"red-link-title","params":["Dian Swastatika Sentosa"]}}' href="https://en.wikipedia.org/wiki/Dian_Swastatika_Sentosa?action=edit&amp;redlink=1" id="mwvQ" rel="mw:WikiLink" title="Dian Swastatika Sentosa (page does not exist)" typeof="mw:LocalizedAttrs">Dian Swastatika Sentosa</a></td>
<td id="mwvg">Mining</td>
<td id="mwvw" style="text-align:center;">5,015</td>
<td id="mwwA" style="text-align:center;">462</td>
<td id="mwwQ" style="text-align:center;">2,368</td>
<td id="mwwg">Jakarta</td>
<td id="mwww">Private</td></tr>
<tr id="mwxA">
<td id="mwxQ">15</td>
<td id="mwxg"><a class="new" data-mw-i18n='{"title":{"lang":"x-page","key":"red-link-title","params":["Erajaya"]}}' href="https://en.wikipedia.org/wiki/Erajaya?action=edit&amp;redlink=1" id="mwxw" rel="mw:WikiLink" title="Erajaya (page does not exist)" typeof="mw:LocalizedAttrs">Erajaya</a></td>
<td id="mwyA">Retail</td>
<td id="mwyQ" style="text-align:center;">3,950</td>
<td id="mwyg" style="text-align:center;">54</td>
<td id="mwyw" style="text-align:center;">5,675</td>
<td id="mwzA">Jakarta</td>
<td id="mwzQ">Private</td></tr>
<tr id="mwzg">
<td id="mwzw">16</td>
<td id="mw0A"><a class="new" data-mw-i18n='{"title":{"lang":"x-page","key":"red-link-title","params":["Bayan Resources"]}}' href="https://en.wikipedia.org/wiki/Bayan_Resources?action=edit&amp;redlink=1" id="mw0Q" rel="mw:WikiLink" title="Bayan Resources (page does not exist)" typeof="mw:LocalizedAttrs">Bayan Resources</a></td>
<td id="mw0g">Coal mining</td>
<td id="mw0w" style="text-align:center;">3,581</td>
<td id="mw1A" style="text-align:center;">1,239</td>
<td id="mw1Q" style="text-align:center;">3,819</td>
<td id="mw1g">Jakarta</td>
<td id="mw1w">Private</td></tr>
<tr id="mw2A">
<td id="mw2Q">17</td>
<td id="mw2g"><a class="new" data-mw-i18n='{"title":{"lang":"x-page","key":"red-link-title","params":["Indah Kiat Pulp &amp; Paper"]}}' href="https://en.wikipedia.org/wiki/Indah_Kiat_Pulp_&amp;_Paper?action=edit&amp;redlink=1" id="mw2w" rel="mw:WikiLink" title="Indah Kiat Pulp &amp; Paper (page does not exist)" typeof="mw:LocalizedAttrs">Indah Kiat Pulp &amp; Paper</a></td>
<td id="mw3A"><a href="https://en.wikipedia.org/wiki/Pulp_and_paper_industry" id="mw3Q" rel="mw:WikiLink" title="Pulp and paper industry">Pulp and paper</a></td>
<td id="mw3g" style="text-align:center;">3,479</td>
<td id="mw3w" style="text-align:center;">412</td>
<td id="mw4A" style="text-align:center;">11,000</td>
<td id="mw4Q">Jakarta</td>
<td id="mw4g">Private</td></tr>
<tr id="mw4w">
<td id="mw5A">18</td>
<td id="mw5Q"><a href="https://en.wikipedia.org/wiki/Indosat" id="mw5g" rel="mw:WikiLink" title="Indosat">Indosat</a></td>
<td id="mw5w"><a href="https://en.wikipedia.org/wiki/Telecommunications" id="mw6A" rel="mw:WikiLink" title="Telecommunications">Telecommunications</a></td>
<td id="mw6Q" style="text-align:center;">3,365</td>
<td id="mw6g" style="text-align:center;">296</td>
<td id="mw6w" style="text-align:center;">4,041</td>
<td id="mw7A">Jakarta</td>
<td id="mw7Q">Private</td></tr>
<tr id="mw7g">
<td id="mw7w">19</td>
<td id="mw8A"><a class="new" data-mw-i18n='{"title":{"lang":"x-page","key":"red-link-title","params":["Indika Energy"]}}' href="https://en.wikipedia.org/wiki/Indika_Energy?action=edit&amp;redlink=1" id="mw8Q" rel="mw:WikiLink" title="Indika Energy (page does not exist)" typeof="mw:LocalizedAttrs">Indika Energy</a></td>
<td id="mw8g"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Oil_and_Gas" id="mw8w" rel="mw:WikiLink" title="Oil and Gas">Oil and gas equipment</a></td>
<td id="mw9A" style="text-align:center;">3,027</td>
<td id="mw9Q" style="text-align:center;">120</td>
<td id="mw9g" style="text-align:center;">3,189</td>
<td id="mw9w">Jakarta</td>
<td id="mw-A">Private</td></tr>
<tr id="mw-Q">
<td id="mw-g">20</td>
<td id="mw-w"><a href="https://en.wikipedia.org/wiki/Garuda_Indonesia" id="mw_A" rel="mw:WikiLink" title="Garuda Indonesia">Garuda Indonesia</a></td>
<td id="mw_Q"><a href="https://en.wikipedia.org/wiki/Airline" id="mw_g" rel="mw:WikiLink" title="Airline">Airline</a></td>
<td id="mw_w" style="text-align:center;">2,937</td>
<td id="mwAQA" style="text-align:center;">250</td>
<td id="mwAQE" style="text-align:center;">4,401</td>
<td id="mwAQI">Jakarta</td>
<td id="mwAQM">SOE</td></tr>
</tbody></table>

In [33]:
soup.find_all('th')

[<th id="mwHQ">Rank</th>,
 <th id="mwHg">Name</th>,
 <th id="mwHw">Industry</th>,
 <th id="mwIA">Revenue<br id="mwIQ"/><small id="mwIg">(USD millions)</small></th>,
 <th id="mwIw">Profits<br id="mwJA"/><small id="mwJQ">(USD millions)</small></th>,
 <th id="mwJg">Employees</th>,
 <th id="mwJw">Headquarters</th>,
 <th id="mwKA">Type</th>,
 <th align="center" id="mwARI">Rank</th>,
 <th align="center" id="mwARM">Forbes <br id="mwARQ"/>2000 rank</th>,
 <th align="center" id="mwARU">Name</th>,
 <th align="center" id="mwARY">Headquarters</th>,
 <th align="center" id="mwARc">Revenue<br id="mwARg"/>(billions <br id="mwARk"/>US$)</th>,
 <th align="center" id="mwARo">Profit<br id="mwARs"/>(billions <br id="mwARw"/>US$)</th>,
 <th align="center" id="mwAR0">Assets<br id="mwAR4"/>(billions <br id="mwAR8"/>US$)</th>,
 <th align="center" id="mwASA">Value<br id="mwASE"/>(billions <br id="mwASI"/>US$)</th>,
 <th align="center" id="mwASM">Industry</th>]

In [34]:
world_titles = table.find_all('th')

In [35]:
world_titles

[<th id="mwHQ">Rank</th>,
 <th id="mwHg">Name</th>,
 <th id="mwHw">Industry</th>,
 <th id="mwIA">Revenue<br id="mwIQ"/><small id="mwIg">(USD millions)</small></th>,
 <th id="mwIw">Profits<br id="mwJA"/><small id="mwJQ">(USD millions)</small></th>,
 <th id="mwJg">Employees</th>,
 <th id="mwJw">Headquarters</th>,
 <th id="mwKA">Type</th>]

In [36]:
world_table_titles = [title.text.strip() for title in world_titles]

print(world_table_titles)

['Rank', 'Name', 'Industry', 'Revenue(USD millions)', 'Profits(USD millions)', 'Employees', 'Headquarters', 'Type']

In [37]:
import pandas as pd

In [38]:
df = pd.DataFrame(columns = world_table_titles)

df

Empty DataFrame
Columns: [Rank, Name, Industry, Revenue(USD millions), Profits(USD millions), Employees, Headquarters, Type]
Index: []

In [39]:
column_data = table.find_all('tr')

In [40]:
for row in column_data [1:]:
    row_data = row.find_all('td')
    individual_row_data = [data.text.strip() for data in row_data]
    
    length = len(df)
    df.loc[length] = individual_row_data

In [41]:
df

,Rank,Name,Industry,Revenue(USD millions),Profits(USD millions),Employees,Headquarters,Type
0,1,Pertamina,Oil and Gas,"75,788","4,441","40,415",Jakarta,SOE
1,2,Perusahaan Listrik Negara,Utilities,"32,013","1,446","51,245",Jakarta,SOE
2,3,Bank Rakyat Indonesia,Banking,"14,917","3,948","77,739",Jakarta,SOE
3,4,Bank Mandiri,Banking,"11,515","3,616","36,872",Jakarta,SOE
4,5,Telkom Indonesia,Telecommunications,"9,801","1,613","23,064",Jakarta,SOE
5,6,Gudang Garam,Tobacco,"7,813",350,"25,961",Kediri,Private
6,7,Bank Central Asia,Banking,"7,371","3,195","25,486",Jakarta,Private
7,8,Indofood,Food,"7,337",535,"81,367",Jakarta,Private
8,9,Inalum,Aluminium,"7,088","1,599","10,422",Batubara,SOE
9,10,Alfamart,Retail,"7,025",224,"195,757",Tangerang,Private
10,11,Adaro Energy,Coal mining,"6,518","1,641","14,697",Tabalong,Private
11,12,Bank Negara Indonesia,Banking,"5,448","1,373","27,570",Jakarta,SOE
12,13,Pupuk Kalimantan Timur,Fertilizer,"5,207",407,"7,441",Bontang,SOE
13,14,Dian Swastatika Sentosa,Mining,"5,015",462,"2,368",Jakarta,Private
14,15,Erajaya,Retail,"3,950",54,"5,675",Jakarta,Private
15,16,Bayan Resources,Coal mining,"3,581","1,239","3,819",Jakarta,Private
16,17,Indah Kiat Pulp & Paper,Pulp and paper,"3,479",412,"11,000",Jakarta,Private
17,18,Indosat,Telecommunications,"3,365",296,"4,041",Jakarta,Private
18,19,Indika Energy,Oil and gas equipment,"3,027",120,"3,189",Jakarta,Private
19,20,Garuda Indonesia,Airline,"2,937",250,"4,401",Jakarta,SOE

In [42]:
# Save the table into csv file
df.to_csv('/Users/sucifn/Documents/Output python web scraping\Companies.csv', index = False)